### ISSUE TITLE
editor doesn't work

### ISSUE THREAD

**Issue by sebalaini** [CoasterCms/coastercms#81]
I've installed a fresh coaster copy with composer and when I go to `manage theme -> edit -> choose a file` nothing happen, i can't edit any file.

I check the console and there is an error

`jquery-1.12.0.min.js:4 POST http://localhost/admin/themes/loadtemplatefile 500 (Internal Server Error)
send @ jquery-1.12.0.min.js:4
ajax @ jquery-1.12.0.min.js:4
(anonymous) @ 1:518
dispatch @ jquery-1.12.0.min.js:3
r.handle @ jquery-1.12.0.min.js:3`

![coaster](https://user-images.githubusercontent.com/17096352/56745856-0ab45080-6773-11e9-8a48-6fc16f1ff8d5.PNG)

and a warning `misspelled option "enableBasicAutocompletion" ace.js`

I don't want to criticise but we are in 2019, who use Jquery 1.12 nowadays?

A part that, even if I modify the files locally through `C:\xampp\htdocs\bcwebsite\resources\views\themes\coaster2017\` the 404 page seems to don't be updated

If I change the assets I need to delete the cache all the time in order to view them, is there a view to disable cache during development?

I'm using XAMPP on Windows 10. I modified the apache conf to use directly the public folder as a root folder so I can type just localhost without any other path.

**Comment by ghost** [comment]
Have you been able to solve this? I ran into the same issue.

**Comment by sebalaini** [comment]
completely forgot about this, nop I left the project.
