### ISSUE TITLE
Is there a way to write new admin module or override existing admin module as per requirements?

### ISSUE THREAD

**Issue by vrdvishwas** [CoasterCms/coastercms#84]
Hi,
I want to write new admin module in CMS for my client. he wants additional form module form for lead generation.
so I just need help to override existing admin route and admin layouts with the help of COASTCMS control or file extends.

**Comment by chadanuk** [comment]
@vrdvishwas Thanks for looking into Coaster . and thanks for asking.

We admit the docs are lacking in this respect. It isn't too tricky, it just requires a little database manipulation (I suggest a seed to add the menu item)

Essentially:

1. Add an admin controller and action to the db (`admin_controllers`, `admin_menus`). Then add an admin menu (`admin_menus`)
1. You should be able to create an `admin` folder in `resources/views`
1. Create a listener for the `SetViewPaths` Event 
1. Pass `$adminViews` by reference in to the listener’s handler function and add the path to your view folder to the array of paths
(see https://github.com/Web-Feet/coasterframework/blob/master/src/CmsServiceProvider.php#L82 for where this is fired for reference)
1. Then you can add your own routes using the coaster admin middleware (`->middleware('coaster.admin')` and call any controllers you wish.

**Comment by ghost** [comment]
I don't quite understand which files I should edit for steps 3 and 4. Could you maybe provide some insight on where to do this?

**Comment by chadanuk** [comment]
Create a new listener in `app/Listeners` (`php artisan make:listener AddAdminViewPaths`)

Then register it in the `app/Providers/EventServiceProvider` file to respond to the `SetViewsPath` event as per https://laravel.com/docs/8.x/events#registering-events-and-listeners

In the handler function of the listener, you'll need something like:
```
handler($setViewPaths) {
  $setViewPaths->adminViews[] = base_path('resources/views/admin');

}
```

Then any views in those folders can be used b your controller/actions.

Top copy any styling from the coaster admin, just take a look through the existing admin views.

Hope that helps.

**Comment by ghost** [comment]
I've got the listener set up. I just had a a question about step 1.

I get the controllers/actions part. But where should I add the menu in the database?

**Comment by chadanuk** [comment]
@Hazekaya In `admin_menus`, you can define a menu item.

**Comment by ghost** [comment]
Thanks a bunch!

**Comment by ghost** [comment]
@chadanuk  I have one last question. (I hope it's the last). You said in the steps above that we should add the path to the views to the array of paths. I have followed the link you provided, but I don't know where I am supposed to add the path. And the path is just "resources/views/admin" right?

**Comment by chadanuk** [comment]
` $setViewPaths->adminViews[] = base_path('resources/views/admin');` inside the `handle` method

**Comment by ghost** [comment]
In my route web.php I've got the following line

`Route::get('dashboard', [\App\Http\Controllers\DashboardController::class, 'index'])
        ->name('admin_dashboard');`

Of course the route is part of the coaster.admin middleware group.

When I try to go to that url it shows the original dashboard and not the one I just created.
I am not sure if I missed or overlooked something.

**Comment by neil-jennings** [comment]
I think the dash route is just the admin url with nothing after.

```php
Route::prefix(config('coaster.admin.url'))->get('', fn() => 'My Dash');
```

Can check the route list to see if you route appears anywhere.

`php artisan route:clear` & `php artisan route:list -c`

Also if you are overriding routes you will need to make sure it's after they are initially declared.
So in `app.php` make sure the provider you are using to register the routes comes after Coasters.

```php
CoasterCms\Providers\CoasterRoutesProvider::class,
App\Providers\OverrideRouteServiceProvider::class,
```

**Comment by ghost** [comment]
@neil-jennings I have it like this.

```
/*
          * Package Service Providers...
          */
        CoasterCms\Providers\CoasterRoutesProvider::class,

        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        // App\Providers\BroadcastServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,
```

I have my routes like this
```

Route::group(['middleware' => ['coaster.admin']], function () {
    // Dashboard
    Route::get('', [\App\Http\Controllers\DashboardController::class, 'index'])
        ->name('admin_dashboard');

    
});
```

**Comment by neil-jennings** [comment]
Check the route is prefixed with `config('coaster.admin.url')` 

Other than that it looks like it should work, maybe caches ?

**Comment by ghost** [comment]
Yes that was it.

Thanks a lot!
